server:
  port: 8080
  max-http-request-header-size: 40KB
  
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: smtpTest.Ryu@gmail.com
    password: cmykdsjzcveskvpm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/develog?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
    username: root
    password:
  
  
mybatis:
  type-aliases-package: com.koreaIT.develog.vo
  
custom:
  siteName: develog
  siteMainUri: http://localhost:8080
  emailFrom: no-reply@localhost
  emailFromName: develog
  kakaoApiKey: 24d745a318b8ce262160b63668ec4ce7

  